### ISSUE TITLE
wrong access rights

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.wizard#6]
I have a local branch to fix https://travis-ci.com/github/zopefoundation/z3c.wizard/jobs/429392603 but I cannot push / create a new branch in zopefoundation/z3c.wizard

@mgedmin / @icemac

**Comment by mgedmin** [comment]
I don't know how access is supposed to be configured.  I compared https://github.com/zopefoundation/z3c.wizard/settings/access with https://github.com/zopefoundation/zope.authentication/settings/access and saw that zope.authentication had granted Write to Contributors and Developers but z3c.wizard only granted Write to Contributors.  So I added the Developers group with Write access.

zope.authentication also grants Admin to Administrators and Maintainers, but z3c.wizard doesn't.  I haven't changed that at this time.

**Comment by jugmac00** [comment]
Thank you! -> see #7

**Comment by dataflake** [comment]
@mgedmin In case you didn't notice, changing those access permissions also automatically subscribed all those members of the Developers group, they will now get email for all changes.

**Comment by mgedmin** [comment]
I'm ... sorry?

**Comment by dataflake** [comment]
No, this was just an FYI in case you weren't aware.
